# Generated by Django 4.2.4 on 2023-09-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPResult',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('AccountID', models.IntegerField()),
                ('AccountName', models.CharField(max_length=20)),
                ('Status', models.IntegerField()),
                ('CreateDate', models.DateField()),
            ],
        ),
    ]
